name: Publish Python-helloworld Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: linux/amd64,linux/arm64
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: python-helloworld:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  